//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplyChain.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupplyChain.Client.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Grid_Delete {
            get {
                return ResourceManager.GetString("Grid_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registros para mostrar.
        /// </summary>
        internal static string Grid_EmptyRecord {
            get {
                return ResourceManager.GetString("Grid_EmptyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Excel.
        /// </summary>
        internal static string Grid_Excelexport {
            get {
                return ResourceManager.GetString("Grid_Excelexport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrastre un encabezado de columna aquí para agrupar la columna.
        /// </summary>
        internal static string Grid_GroupDropArea {
            get {
                return ResourceManager.GetString("Grid_GroupDropArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Última página.
        /// </summary>
        internal static string Grid_LastPage {
            get {
                return ResourceManager.GetString("Grid_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente página.
        /// </summary>
        internal static string Grid_NextPage {
            get {
                return ResourceManager.GetString("Grid_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        internal static string Grid_Print {
            get {
                return ResourceManager.GetString("Grid_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Grid_Save {
            get {
                return ResourceManager.GetString("Grid_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Grid_SaveButton {
            get {
                return ResourceManager.GetString("Grid_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Grid_Search {
            get {
                return ResourceManager.GetString("Grid_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} de {1} páginas.
        /// </summary>
        internal static string Pager_CurrentPageInfo {
            get {
                return ResourceManager.GetString("Pager_CurrentPageInfo", resourceCulture);
            }
        }
    }
}
