//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupplyChain.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupplyChain.Client.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Grid_Delete {
            get {
                return ResourceManager.GetString("Grid_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay registros para mostrar.
        /// </summary>
        internal static string Grid_EmptyRecord {
            get {
                return ResourceManager.GetString("Grid_EmptyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar Excel.
        /// </summary>
        internal static string Grid_Excelexport {
            get {
                return ResourceManager.GetString("Grid_Excelexport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrastre un encabezado de columna aquí para agrupar la columna.
        /// </summary>
        internal static string Grid_GroupDropArea {
            get {
                return ResourceManager.GetString("Grid_GroupDropArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última página.
        /// </summary>
        internal static string Grid_LastPage {
            get {
                return ResourceManager.GetString("Grid_LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente página.
        /// </summary>
        internal static string Grid_NextPage {
            get {
                return ResourceManager.GetString("Grid_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        internal static string Grid_Print {
            get {
                return ResourceManager.GetString("Grid_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Grid_Save {
            get {
                return ResourceManager.GetString("Grid_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Grid_SaveButton {
            get {
                return ResourceManager.GetString("Grid_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string Grid_Search {
            get {
                return ResourceManager.GetString("Grid_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} de {1} páginas.
        /// </summary>
        internal static string Pager_CurrentPageInfo {
            get {
                return ResourceManager.GetString("Pager_CurrentPageInfo", resourceCulture);
            }
        }
    }
}
